### ISSUE TITLE
 Functional components usage

### ISSUE THREAD

**Issue by Rudy-Menekam** [Rudy-Menekam/Math-Magicians#5]
I used the following steps below to implement my Calculator app

1. First I created a new react project using the commands; 
             -  npx create-react-app math-magic,
             - Set up eslint and style lint.
2. Created a component directory that contained a calcultor.js file as a parent component and also a logic directory, that contained the calculate.js and operate.js files respectively, which I imported in the calculator.js file.
3. The Calculator component in calculator.js is defined as a function using the function keyword. This is the syntax for defining a functional component in React.
4. Created 1 child component (keys-function) where I made the UX design for the calculator function keys, then I  imported it in the calculator.js file that I finally used in the app.js.
5. I used the useState hook which I imported into the calculator.js, to initiate the state of the app.
6. I created an onClickhandler method which I called in the buttons to implement the functions.

**Comment by GedeonTS** [comment]
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Rudy-Menekam ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- Good use of React hooks :clap: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
